dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: X9vVLQZ2N7Z66Ug7PocDOF1wxlNGzLqKLWnvMOTUBRVe7wRm5cm224RAbm4neyGs4wDlFFGEfJgWZtjZFqYpBkM3iWvtHv+N5n0wpk/uKcUtH7SKs1sL7A0MQhScctvDistG4iUsvxUtEGjOnnJpLEiy/BaQLzJZGiKln6ygcE7zuw0jJpgvBRTdjq6U6ggaOuleFEl4FfI6mUiUeUAu/8ISwMu3BRmSUU6z0OqIWDruGnU4S30pGHJh5Ddgqj039wBxJAQvZyOaAWAFqNjvkuRQuFTnZeZKnJYP8hxm5RqujUxwSgPAspMKbHEsuNvG959HSsLNhO8vVKADL4SdWaee+dmaM6bpRCY8u5RZvce2JvxfuOgcBJjRowuRHHkFKK0HcEMhRLaT1tefyNneh6HUxehj5jgXpmmdo5vBkg8CMpM0dzq5851IajbYlQ+vefgZvmP6RfUWXpVZNwj2EdWIXrHpMvlu67J/W6hwfpeBmDoxyHHAy7pp2mwLEtQh5DXSpjm7SoEOvlLp+fDGRhk7u52lknZJRjGf+M3FTY4qNkRagCgkIZukh8ADEjJx2/8SSp4mzuA8/p4bUYhLO2hoLDq2+1sPZolJ7+bIh1+/HOd+yUEML1U+uIfxabNHRn/c+3vlgDRMG2fIpk5/7IM9TsxAKbwsaGu+CtEdXHM=
